CREATE DATABASE IF NOT EXISTS `UserCenter` CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'BronzeSword'@'%' IDENTIFIED BY '12345678';
GRANT ALL PRIVILEGES ON UserCenter.* TO 'BronzeSword'@'%';
FLUSH PRIVILEGES;
